config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static#home'
  devise_scope :user do
    get 'signup' => 'devise/registrations#new'
    get '/login' => 'devise/sessions#new'
    delete '/logout' => 'devise/sessions#destroy'
  end


  resources :movies do
    resources :characters, only: [:new,:create,:destroy,:index]
  end
  resources :people
  resources :reviews
  resources :genres, only: [:index, :new, :create, :show]
  resources :users,  only: [:show]
   #[:index,:directed_movies,:written_movies,:filmography]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/people/:id/directed_movies' => 'people#directed_movies', as: 'directed_movies'
  get '/people/:id/written_movies' => 'people#written_movies', as: 'written_movies'
  get '/people/:id/filmography' => 'people#filmography', as: 'filmography'

  get '*path' => 'static#home'
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :characters, :foreign_key=>'actor_id'
  has_many :movies, through: :characters, :foreign_key => 'actor_id'
  has_many :directed_movies, :foreign_key => 'director_id', :class_name=>'Movie'
  has_many :written_movies, :foreign_key => 'writer_id', :class_name=>'Movie'
  validates :name, presence: true
  validates :name, uniqueness: { scope: :dob}
  after_validation :set_slug, only: [:create, :update]

  def directed_movies
    Movie.where(director: self).order(release_date: :desc)
  end

  def written_movies
    Movie.where(writer: self).order(release_date: :desc)
  end

  def characters_played
    Character.where(actor:self).sort { |x,y| y.movie.release_date<=> x.movie.release_date }
  end

  private
    def set_slug
      if self.dob.present?
        self.slug = "#{name.to_s.parameterize}-#{dob.to_s.parameterize}"
      else
        self.slug = name.to_s.parameterize
      end
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people||=Person.order(:name)
    @directors||=@people.select{|person| !person.directed_movies.empty?}
    @writers||=@people.select{|person| !person.written_movies.empty?}
    @actors||=@people.select{|person| !person.characters.empty?}
  end

  def new
    @person=Person.new
  end

  def create
    @person=Person.create(person_params)
    redirect_to person_path(@person.slug)
  end

  def show
    if person_identify
      @characters=@person.characters_played
      @written_movies=@person.written_movies
      @directed_movies=@person.directed_movies
    else
      redirect_to people_path
    end
  end

  def edit
    if person_identify
    else
      redirect_to people_path
    end
  end

  def update
    @person=Person.find(params[:id])
    @person.update(person_params)
    redirect_to person_path(@person.slug)
  end

  def destroy
    if person_identify
      @characters=@person.characters_played
      @characters.each do |character|
        character.destroy
      end
      @person.destroy
      redirect_to people_path
    else
      redirect_to people_path
    end
  end

  def directed_movies
    if person_identify
      if !@person.directed_movies.empty?
        @movies=@person.directed_movies
      else
        redirect_to person_path(@person.slug)
      end
    else
      redirect_to people_path
    end
  end

  def written_movies
    if person_identify
      if !@person.written_movies.empty?
        @movies=@person.written_movies
      else
        redirect_to person_path(@person.slug)
      end
    else
      redirect_to people_path
    end
  end

  def filmography
    if person_identify
      if !@person.characters_played.empty?
        @characters=@person.characters_played
      else
        redirect_to person_path(@person.slug)
      end
    else
      redirect_to people_path
    end
  end

  private

  def person_identify
    @person||=Person.find_by(:slug=> params[:id])
  end

  def person_params
    params.require(:person).permit(:name,:dob)
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_filmography.html.erb
<ul>
  <% characters.each do |character|%>
  <li><%=link_to character.movie.title, movie_path(character.movie.slug)%> - <%=character.movie.release_date%><br>
  <%=character.name%></li>
  <%end%>
</ul>

app/views/people/_form.html.erb
<%= form_for person do |f| %>
<table>
  <tr>
    <td><%= f.label :name%></td>
    <td><%= f.text_field :name%></td>
  </tr>
<tr>
  <td><%= f.label :dob, 'Date of Birth'%></td>
  <td><%= f.date_field :dob%>
</td>
</tr>
<tr>
<td><%= f.submit %></td>
</tr>
</table>
<% end %>

app/views/people/_people_list.html.erb
<ul>
  <% people.each do |p|%>
  <li><%=link_to p.name, person_path(p.slug)%></li>
  <%end%>
</ul>

app/views/people/directed_movies.html.erb
<h1>Movies directed by <%=@person.name%></h1>
<%= render partial:'movie_list', locals: {movies: @movies} %>

<%= link_to "<button>Go back</button>".html_safe, :back, :id => "button_id", :class => "button_class"%>

app/views/people/edit.html.erb
<h1>Edit <%=@person.name%></h1>

<%= render partial:'form', locals: {person: @person} %>
<%= link_to "<button>Go back</button>".html_safe, :back, :id => "button_id", :class => "button_class"%>

app/views/people/filmography.html.erb
<h1><%=@person.name%> Filmography</h1>
<%= render partial:'filmography', locals: {characters: @characters} %>


<%= link_to "<button>Go back</button>".html_safe, :back, :id => "button_id", :class => "button_class"%> 

app/views/people/index.html.erb
<h1>All people in the database are listed below</h1>
<%= link_to "<button>Add new person</button>".html_safe, new_person_path, :id => "button_id", :class => "button_class" if user_signed_in?%>
<table>
  <thead>
    <th><h3>Actors</h3></th>
    <th><h3>Directors</h3></th>
    <th><h3>Writers</h3></th>
  </thead>
  <tr valign="top">
    <td><%= render partial:'people_list', locals: {people: @actors} %>
    </td>
    <td><%= render partial:'people_list', locals: {people: @directors} %>
    </td>
    <td><%= render partial:'people_list', locals: {people: @writers} %>
    </td>
  </tr>
</table>

app/views/people/new.html.erb
<h1>Add new person</h1>

<%= render partial:'form', locals: {person: @person} %>

app/views/people/show.html.erb
<h1><%=@person.name%></h1>
<h2><%="Director " if !@directed_movies.empty?%><%="Writer " if !@written_movies.empty?%><%="Actor" if !@characters.empty?%></h2>
<h2>Date of Birth: <%=@person.dob%></h2>


<% if !@directed_movies.empty?%>
<h3><%=link_to "Directed Movies", directed_movies_path(@person.slug) %></h3>
<%= render partial:'movie_list', locals: {movies: @directed_movies} %>


<%end%>

<% if !@written_movies.empty?%>
<h3><%=link_to "Written Movies", written_movies_path(@person.slug) %></h3>
<%= render partial:'movie_list', locals: {movies: @written_movies} %>
<%end%>

<% if !@characters.empty?%>
<h3><%=link_to "Filmography", filmography_path(@person.slug) %></h3>
<%= render partial:'filmography', locals: {characters: @characters} %>
<%end%>
<p><%= link_to "<button>Go back</button>".html_safe, :back, :id => "button_id", :class => "button_class"%><%=link_to "<button>Edit</button>".html_safe, edit_person_path(@person.slug),:id => "button_id", :class => "button_class" if user_signed_in? %><%=link_to '<button>Delete</button>'.html_safe, person_path(@person.slug),
            data: {:confirm => 'Are you sure?'}, :method => :delete,:id => "button_id", :class => "button_class" if user_signed_in? %></p>

app/views/people/written_movies.html.erb
<h1>Movies written by <%=@person.name%></h1>
<%= render partial:'movie_list', locals: {movies: @movies} %>

<%= link_to "<button>Go back</button>".html_safe, :back, :id => "button_id", :class => "button_class"%>