config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static#home'
  devise_scope :user do
    get 'signup' => 'devise/registrations#new'
    get '/login' => 'devise/sessions#new'
    delete '/logout' => 'devise/sessions#destroy'
  end


  resources :movies do
    resources :characters, only: [:new,:create,:destroy,:index]
  end
  resources :people
  resources :reviews
  resources :genres, only: [:index, :new, :create, :show]
  resources :users,  only: [:show]
   #[:index,:directed_movies,:written_movies,:filmography]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/people/:id/directed_movies' => 'people#directed_movies', as: 'directed_movies'
  get '/people/:id/written_movies' => 'people#written_movies', as: 'written_movies'
  get '/people/:id/filmography' => 'people#filmography', as: 'filmography'

  get '*path' => 'static#home'
end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many :movie_genres
  has_many :genres, through: :movie_genres
  belongs_to :director, class_name:"Person", optional: true
  belongs_to :writer, class_name:"Person", optional: true
  has_many :characters
  has_many :actors, :through => :characters, :source => :actor
  has_many :reviews
  has_many :users, through: :reviews
  validates :title, presence: true
  validates :title, uniqueness: { scope: :release_date}
  after_validation :set_slug, only: [:create, :update]
  accepts_nested_attributes_for :movie_genres,:director,:writer, :characters

  def genres_attributes=(genre_attributes)
   genre_attributes.values.each do |genre_attribute|
     if genre_attribute["name"].present?
       genre = Genre.find_or_create_by(genre_attribute)
      # self.genres << genre
       self.movie_genres.build(genre: genre)
     end
   end
 end

 def director_attributes=(director_attribute)
   if director_attribute[:name].present?
     if person=person_find_by(director_attribute)
       self.director=person
     else
      self.build_director(director_attribute)
     end
   end
 end

  def writer_attributes=(writer_attribute)
      if writer_attribute[:name].present?
        if person=person_find_by(writer_attribute)
          self.writer=person
        elsif self.director && self.director.name==writer_attribute[:name] && self.director.dob.to_s==writer_attribute[:dob]
            self.writer=self.director
        else
         self.build_writer(writer_attribute)
        end
      end
   end

   def characters_attributes=(characters_attributes)
    characters_attributes.values.each do |character_attributes|
      if character_attributes["actor_id"].present?
        self.characters.build(actor_id: character_attributes[:actor_id],name: character_attributes[:name]) unless self.actors.include?(Person.find(character_attributes["actor_id"]))
      else
        if character_attributes[:actor_attributes][:name].present?
          if self.director && self.director.name==character_attributes[:actor_attributes][:name] && self.director.dob.to_s==character_attributes[:actor_attributes][:dob]
            self.actors << self.director
            self.characters.last.name=character_attributes[:name]
          elsif self.writer && self.writer.name==character_attributes[:actor_attributes][:name] && self.writer.dob.to_s==character_attributes[:actor_attributes][:dob]
            self.actors << self.writer
            self.characters.last.name=character_attributes[:name]
          else
            person=Person.find_or_create_by(character_attributes[:actor_attributes])
            self.characters.build(actor_id: person.id,name: character_attributes[:name])
          end
        end
      end
    end
  end

  private

    def set_slug
      if self.release_date.present?
        self.slug = "#{title.to_s.parameterize}-#{release_date.to_s.parameterize}"
      else
        self.slug = title.to_s.parameterize
      end
    end



  #  def director_attributes=(director_attribute)  ### - OLD CODE GOOD FOR DIRECTOR AND WRITER
  #    if director_attribute[:name].present?
  #      if director = Person.find_by(director_attribute)
  #        self.director=director
  #      elsif director = Person.where(dob: nil).find_by(name: #director_attribute[:name])
  #        self.director=director
  #      else
  #       self.build_director(director_attribute)
  #      end
  #    end
  #  end


end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies||= Movie.order(:title)
    @genres||= Genre.order(:name)

  end

  def new
    @movie=Movie.new
    @genres||=Genre.order(:name)
    @people||=Person.order(:name)
    5.times {@movie.characters.build}
    #@movie.build_director
  end

  def create
    @movie=Movie.new(movie_params)
    if @movie.save
      redirect_to movie_path(@movie.slug)
    else
      redirect_to new_movie_path, alert: @movie.errors.full_messages
    end
  end

  def show
    if @movie=Movie.find_by(:slug=> params[:id])
      @director=@movie.director
      @writer=@movie.writer
      @genres=@movie.genres.uniq
      @characters=@movie.characters.order(:name)
    else
      redirect_to movies_path
    end
  end

  def edit
    if @movie=Movie.find_by(:slug=> params[:id])
      @genres||=Genre.order(:name)
      @people||=Person.order(:name)
    else
      redirect_to movies_path
    end
  end

  def update
    @movie=Movie.find(params[:id])
    @movie.update(movie_params)
    redirect_to movie_path(@movie.slug)
  end

  def destroy
    if @movie=Movie.find_by(:slug=> params[:id])
      @movie.characters.each do |character|
        character.destroy
      end
      MovieGenre.all.each do |movie_genre|
        if movie_genre.movie == @movie
          movie_genre.destroy
        end
      end
      @movie.destroy
      redirect_to movies_path
    else
      redirect_to movies_path
    end
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :director_id,:writer_id,:release_date, genre_ids:[], genres_attributes: [:name], director_attributes: [:name, :dob],writer_attributes: [:name, :dob],characters_attributes: [:movie_id, :actor_id,:name, actor_attributes:[:name,:dob]])
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for movie do |f| %>

<table>
  <tr>
    <td><h3><%= f.label :title%></h3></td>
    <td><%= f.text_field :title%></td>
    <td><h3><%= f.label :release_date%></h3></td>
    <td><%= f.number_field :release_date%></td>
  </tr>
<tr>
  <td><h3>Genres:</h3></td>
  <td><%= f.select :genre_ids, options_from_collection_for_select(@genres, :id, :name, f.object.genre_ids), {}, {:multiple => true} %></td> 
  <td>Or create a new genre:</td>
  <%= f.fields_for :genres, movie.genres.build do |genres_fields| %>
    <td><%= genres_fields.text_field :name %></td>
  <% end %>
</tr>
<tr>
  <td><h3><%= f.label :director%></h3></td>
  <td><%=  f.collection_select :director_id, @people,:id,:name, include_blank: true %></td>
  <td>Or create a new director:</td>
  <%= f.fields_for :director, movie.build_director do |director_attribute|%>
    <td><%= director_attribute.text_field :name %></td>
    <td><%= director_attribute.label :dob, "DOB:" %></td>
    <td><%= director_attribute.date_field :dob %></td>
  <% end %>
</tr>
<tr>
  <td><h3><%= f.label :writer%></h3></td>
  <td><%=  f.collection_select :writer_id, @people,:id,:name, include_blank: true %></td>
  <td>Or create a new writer:</td>
  <%= f.fields_for :writer, movie.build_writer do |writer_attribute|%>
    <td><%= writer_attribute.text_field :name %></td>
    <td><%= writer_attribute.label :dob, "DOB:" %></td>
    <td><%= writer_attribute.date_field :dob %></td>
  <% end %>
</tr>
<tr>
  <td><h3>Cast</h3></td>
</tr>
<%= f.fields_for :characters do |character_fields| %>

<tr>

  <td> <strong>Actor:</strong></td>
  <td><%=  character_fields.collection_select :actor_id, @people,:id,:name, include_blank: true %></td>
  <td><strong> Character Name:</strong></td>
  <td><%=character_fields.text_field :name%></td>
  <td>Or create a new actor:</td>
  <%= character_fields.fields_for :actor, movie.actors.build do |actor_attribute| %>
    <td><%= actor_attribute.text_field :name %></td>
    <td><%= actor_attribute.label :dob, "DOB:" %></td>
    <td><%= actor_attribute.date_field :dob %></td>
  </tr>

  <% end %>
  <% end %>

<tr>

</tr>
<tr>
  <td><%= f.submit %></td>
</tr>
</table>
<% end %>

app/views/movies/_new_movie.html.erb
<%= form_for movie do |f| %>
<table>
  <tr>
    <td><%= f.label :title%></td>
    <td><%= f.text_field :title%></td>
  </tr>
<tr>
  <td>Genres:</td>
    <td><%= f.select :genre_ids, options_from_collection_for_select(@genres, :id, :name), {}, {:multiple => true} %></td>


  <td>Or create a new genre:</td>

  <td><%= f.fields_for :genres, movie.genres.build do |genres_fields| %>
  <%= genres_fields.text_field :name %></td>
<% end %>
</tr>
<tr>
  <td><%= f.label :director%></td>
  <td><%=  f.collection_select :director_id, Person.order(:name),:id,:name, include_blank: true %></td>

  <td>Or create a new director:</td>
    <%= f.fields_for :director, movie.build_director do |director_attribute|%>
        <td>
        <%= director_attribute.text_field :name %>
    </td><td><%= director_attribute.label :dob, "DOB:" %></td><td>
    <%= director_attribute.date_field :dob %>
</td>
  <% end %>
</tr>
<!-- <tr>
  <td><%= f.label :writer%></td>
  <td><%= f.collection_select :writer_id, Person.order(:name),:id,:name, include_blank: true %></td>
  <td>Or create a new writer:</td>
    <%= f.fields_for :writer, movie.build_writer do |writer_attributes|%>
        <td><%= writer_attributes.label :name, "Name:" %></td><td>
        <%= writer_attributes.text_field :name %>
    </td><td><%= writer_attributes.label :dob, "DOB:" %></td><td>
    <%= writer_attributes.date_field :dob %>
</td>
    <% end %>
</tr> -->
<tr>
  <td><%= f.label :release_date%></td>
  <td><%= f.number_field :release_date%>
</td>
</tr>
<tr>
<td><%= f.submit %></td>
</tr>
</table>
<% end %>

app/views/movies/edit.html.erb
<h1>Edit <%=@movie.title%></h1>

<%= render partial:'form', locals: {movie: @movie} %>
<%= link_to "<button>Go back</button>".html_safe, movie_path(@movie.slug), :id => "button_id", :class => "button_class" if user_signed_in?%>

app/views/movies/index.html.erb
<%= link_to "<button>Add new movie</button>".html_safe, new_movie_path, :id => "button_id", :class => "button_class" if user_signed_in?%>
<h1>All Movies</h1>
<h3>See movies by Genre</h3>
<h4><% @genres.each do |genre|%>
<%= link_to genre.name, genre_path(genre.slug)%>(<%=genre.movies.size%>)
<%end%></h4>

<%= render partial:'movie_list', locals: {movies: @movies} %>

app/views/movies/new.html.erb
<h1>Add new movie</h1>

<%= render partial:'form', locals: {movie: @movie} %>

app/views/movies/show.html.erb
<h1><%=@movie.title%></h1>
<h2>
<% @genres.each do |genre|%>
<%=link_to genre.name, genre_path(genre.slug) %>
<% end%></h2>
<h2>Release Date: <%=@movie.release_date%></h2>
<h3>Director: <%=link_to @director.name, person_path(@director.slug) if !@director.nil?%></h3>
<h3>Writer: <%=link_to @writer.name, person_path(@writer.slug) if !@writer.nil?%></h3>
<h3><%=link_to "Cast", movie_characters_path(@movie.slug)%></h3>
<%= link_to "<button>Add new cast member</button>".html_safe, new_movie_character_path(@movie.slug), :id => "button_id", :class => "button_class" if user_signed_in?%>
<table>
  <thead>
    <th>Actor</th>
    <th>Character</th>
  </thead>
  <% @characters.each do |character| %>
  <tr>
    <td><%=link_to character.actor.name, person_path(character.actor.slug)%></td>
    <td><%=character.name%></td>
    <td><%= link_to "<button>x</button>".html_safe, movie_character_path(@movie.slug,character), :method=> :delete,:id => "button_id", :class => "button_class" if user_signed_in?%>
  </tr>
  <%end%>
</table>

<p><%= link_to "<button>Go back</button>".html_safe, :back, :id => "button_id", :class => "button_class"%><%=link_to "<button>Edit</button>".html_safe, edit_movie_path(@movie.slug),:id => "button_id", :class => "button_class" if user_signed_in? %><%=link_to '<button>Delete</button>'.html_safe, movie_path(@movie.slug),
            data: {:confirm => 'Are you sure?'}, :method => :delete,:id => "button_id", :class => "button_class" if user_signed_in? %></p>