config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static#home'
  devise_scope :user do
    get 'signup' => 'devise/registrations#new'
    get '/login' => 'devise/sessions#new'
    delete '/logout' => 'devise/sessions#destroy'
  end


  resources :movies do
    resources :characters, only: [:new,:create,:destroy,:index]
  end
  resources :people
  resources :reviews
  resources :genres, only: [:index, :new, :create, :show]
  resources :users,  only: [:show]
   #[:index,:directed_movies,:written_movies,:filmography]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/people/:id/directed_movies' => 'people#directed_movies', as: 'directed_movies'
  get '/people/:id/written_movies' => 'people#written_movies', as: 'written_movies'
  get '/people/:id/filmography' => 'people#filmography', as: 'filmography'

  get '*path' => 'static#home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
 var idx=window.location.toString().indexOf("#_=_");
   if (idx > 0) {
     window.location = window.location.toString().substring(0, idx);
   }
</script>
  </head>
  <nav class='nav'>

  <ul>
    <li><%= link_to 'Home', root_path%></li>
    <li><%= link_to 'Movies', movies_path%></li>
    <li><%= link_to 'People', people_path%></li>
    <!-- <li><%= link_to 'Reviews', reviews_path%></li> -->
    <% if user_signed_in? %>
      <li style="float:right"><%= link_to 'Logout', destroy_user_session_path, method: :delete%></li>
      <li style="float:right"><%= link_to 'Edit Profile', edit_user_registration_path%></li>
      <!-- <li style="float:right"><%= link_to 'My Profile', user_path(current_user)%></li> -->

    <%else%>
      <li style="float:right"><%= link_to 'Sign up', signup_path%></li>
      <li style="float:right"><%= link_to 'Login', login_path%></li>
    <%end%>
  </ul>

</nav>
  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>